### ISSUE TITLE
Documenting my setup process

### ISSUE THREAD

**Issue by g-simmons** [geneshairzan/qmk_layer_notification#1]
Hey @geneshairzan, thanks for creating this. I've wanted a tool like this for a while. My goal is to show the cheatsheet for each layer of my keyboard when the layer is active. Ideally in a transparent overlay/HUD.

I'm just putting my setup log here in case it is useful to you or others...

## Environment Details

Operating System: MacOS Catalina
Keyboard: [Keyball61](https://github.com/Yowkees/keyball)

## Setting up this repo and dependencies

I cloned this repo as instructed in the README.

I ran into an issue when attempting to do `node list` - this was due to wrong node version. I am using nvm on my system, so I switched using `nvm use 18`. `node list` worked properly after that. 

I was a little confused about the `index` field in config.js, but I guess this is necessary if you have two HID devices with the same product ID. I don't think that's the case for me, so I set index to 0. It might be useful to change index to 0 in the config.js in this repo, since that is probably more likely for most users. 

I already had QMK installed, this is probably the case for most users. This involves cloning [this repo](https://github.com/qmk/qmk_firmware) to your machine. Other commands below that refer to qmk_firmware are referring to this directory.

## Modifying keymap.c

In my case, the relevant keymap.c file was at qmk_firmware/keyboards/keyball/keyball61/keymaps/via/keymap.c. I found a function in there that looks like it has something to do with layer state, so I added the `include "print.h"` at the top of the file, then added the uprintf line to the function shown below. I was wrong about this function, see below.

```c
layer_state_t layer_state_set_user(layer_state_t state) {
    // Auto enable scroll mode when the highest layer is 3
    keyball_set_scroll_mode(get_highest_layer(state) == 3);
    uprintf("layer%u", state);
    return state;
}
```

## Building the modified firmware

Then had to rebuild the firmware. From the root directory of `qmk_firmware`, I did `make keyball/keyball61:via` and got the following output.

```
QMK Firmware 0.17.0
☒ keyball/keyball61: NO_ACTION_MACRO in config.h is no longer a valid option
☒ keyball/keyball61: NO_ACTION_FUNCTION in config.h is no longer a valid option
Making keyball/keyball61 with keymap via

☒ keyball/keyball61: NO_ACTION_MACRO in config.h is no longer a valid option
☒ keyball/keyball61: NO_ACTION_FUNCTION in config.h is no longer a valid option
avr-gcc (Homebrew AVR GCC 9.4.0) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Size before:
   text    data     bss     dec     hex filename
      0   27074       0   27074    69c2 keyball_keyball61_via.hex

Compiling: keyboards/keyball/keyball61/keymaps/via/keymap.c                                         [OK]
Compiling: quantum/via.c                                                                            [OK]
Linking: .build/keyball_keyball61_via.elf                                                           [OK]
Creating load file for flashing: .build/keyball_keyball61_via.hex                                   [OK]
Copying keyball_keyball61_via.hex to qmk_firmware folder                                            [OK]
Checking file size of keyball_keyball61_via.hex                                                     [OK]
 * The firmware size is fine - 27074/28672 (94%, 1598 bytes free)
```

## Flashing new firmware

Next step is to flash the new firmware to the keyboard itself. If you are using a custom layout via REMAP https://remap-keys.app/, the first time I did this it reset my keymap. This didn't happen on subsequent flashes though, not sure why. I suggest to save it on remap before proceeding, just in case.

This is done with `qmk flash` CLI command, with `-kb` and `-km` arguments specifying the keyboard and keymap. I used `qmk list-keyboards` to find the exact keyboard name.

Then did

```
qmk flash -kb keyball/keyball61 -km via 
```

and got 

```
qmk flash -kb keyball/keyball61 -km via  Py mft_textgen Node 18.7.0
Ψ Compiling keymap with gmake --jobs=1 keyball/keyball61:via:flash


QMK Firmware 0.17.0
☒ keyball/keyball61: NO_ACTION_MACRO in config.h is no longer a valid option
☒ keyball/keyball61: NO_ACTION_FUNCTION in config.h is no longer a valid option
Making keyball/keyball61 with keymap via and target flash

☒ keyball/keyball61: NO_ACTION_MACRO in config.h is no longer a valid option
☒ keyball/keyball61: NO_ACTION_FUNCTION in config.h is no longer a valid option
avr-gcc (Homebrew AVR GCC 9.4.0) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Size before:
   text    data     bss     dec     hex filename
      0   27074       0   27074    69c2 keyball_keyball61_via.hex

Compiling: quantum/via.c                                                                            [OK]
Linking: .build/keyball_keyball61_via.elf                                                           [OK]
Creating load file for flashing: .build/keyball_keyball61_via.hex                                   [OK]
Copying keyball_keyball61_via.hex to qmk_firmware folder                                            [OK]
Checking file size of keyball_keyball61_via.hex                                                     [OK]
 * The firmware size is fine - 27074/28672 (94%, 1598 bytes free)
Waiting for USB serial port - reset your controller now (Ctrl+C to cancel)............
```

## Putting KB into bootloader mode

My keyboard is a split keyboard with two ProMicros, there is a small reset button next to each controller. Pressing the button while the `qmk flash` command was running resulted in:

```
Waiting for USB serial port - reset your controller now (Ctrl+C to cancel)......
Device /dev/tty.usbmodem1433301 has appeared; assuming it is the controller.
Waiting for /dev/tty.usbmodem1433301 to become writable.

Connecting to programmer: .
Found programmer: Id = "CATERIN"; type = S
    Software Version = 1.0; No Hardware Version given.
Programmer supports auto addr increment.
Programmer supports buffered memory access with buffersize=128 bytes.

Programmer supports the following devices:
    Device code: 0x44

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e9587 (probably m32u4)
avrdude: NOTE: "flash" memory has been specified, an erase cycle will be performed
         To disable this feature, specify the -D option.
avrdude: erasing chip
avrdude: reading input file ".build/keyball_keyball61_via.hex"
avrdude: input file .build/keyball_keyball61_via.hex auto detected as Intel Hex
avrdude: writing flash (27074 bytes):

Writing | ################################################## | 100% 2.07s

avrdude: 27074 bytes of flash written
avrdude: verifying flash memory against .build/keyball_keyball61_via.hex:
avrdude: load data flash data from input file .build/keyball_keyball61_via.hex:
avrdude: input file .build/keyball_keyball61_via.hex auto detected as Intel Hex
avrdude: input file .build/keyball_keyball61_via.hex contains 27074 bytes
avrdude: reading on-chip flash data:

Reading | ################################################## | 100% 0.25s

avrdude: verifying ...
avrdude: 27074 bytes of flash verified

avrdude done.  Thank you.
```

I did this for both sides of the keyboard.

## Enabling QMK debugging

At this point I am thinking that switching layers should give some result after running node index, but I'm not seeing anything.

I looked at https://github.com/qmk/qmk_firmware/blob/master/docs/cli_commands.md#qmk-console which indicates that qmk console cli command can be used to read debug messages, but this requires that you compile your firmware with `CONSOLE_ENABLE = yes`. 

The `CONSOLE_ENABLE` flag for my keyboard was in qmk_firmware/keyboards/keyball/keyball61/rules.mk, I changed it from `no` to `yes`. Then rebuild the firmware with `make keyball/keyball61:via`. 

## Firmware too big 
Setting console_enable unfortunately made the firmware too large, see below:

```
...
Compiling: lib/lufa/LUFA/Drivers/USB/Core/DeviceStandardReq.c                                       [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/Events.c                                                  [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/HostStandardReq.c                                         [OK]
Compiling: lib/lufa/LUFA/Drivers/USB/Core/USBTask.c                                                 [OK]
Compiling: tmk_core/protocol/lufa/usb_util.c                                                        [OK]
Linking: .build/keyball_keyball61_via.elf                                                           [OK]
Creating load file for flashing: .build/keyball_keyball61_via.hex                                   [OK]
Copying keyball_keyball61_via.hex to qmk_firmware folder                                            [OK]
Checking file size of keyball_keyball61_via.hex
 * The firmware is too large! 31064/28672 (2392 bytes over)
```

Looked here to try to reduce firmware size: https://www.reddit.com/r/MechanicalKeyboards/comments/aqmd5f/firmware_is_too_large_qmk_firmware/

Already had `COMMAND_ENABLE = no`

Tried adding `EXTRAFLAGS+=-flto` but that didn't do anything, probably because `LTO_ENABLE` is already `yes`

Turning off RGB by setting `RGBLIGHT_ENABLE = no` in `keyboards/keyball/keyball61/keymaps/via/rules.mk` reduced the firmware size enough... I like my RGB lights though 😢 

Saved the keymap to REMAP this time so I don't have to remake it by hand... but I didn't need to restore it? Maybe because I had remap browser tab open? Seems unlikely, whatever, less work for me

## Second attempt at modifying keymap.c to get debug messages

Before `qmk console` command stopped at 

```
Looking for devices...
```

Now it shows 

```
Looking for devices...
Ψ Console Connected: Yowkees Keyball61 (5957:0100:1)
```

This seems like progress, but pressing buttons and switching layers doesn't do anything. Maybe the print statement is in the wrong place...

Tried copying these lines from `develop/keymap.c` to `via/keymap.c`

```
void keyboard_post_init_user(void) {
#ifdef CONSOLE_ENABLE
    debug_enable = true;
#endif
}
```

This link https://github.com/qmk/qmk_firmware/blob/master/docs/faq_debug.md suggests to override `process_record_user` function to debug each keypress event.

So added the following code from the above link to `via/keymap.c`.

```c
bool process_record_user(uint16_t keycode, keyrecord_t *record) {
  // If console is enabled, it will print the matrix position and status of each key pressed
#ifdef CONSOLE_ENABLE
    uprintf("KL: kc: 0x%04X, col: %2u, row: %2u, pressed: %u, time: %5u, int: %u, count: %u\n", keycode, record->event.key.col, record->event.key.row, record->event.pressed, record->event.time, record->tap.interrupted, record->tap.count);
#endif 
  return true;
}
```

This worked, got output like the following in qmk console

```
 qmk console                                                                        18s Py miniconda3 Node 18.7.0
Looking for devices...
Ψ Console Connected: Yowkees Keyball61 (5957:0100:1)
jYowkees:Keyball61:1: KL: kc: 0x000D, col:  5, row:  7, pressed: 1, time:  6421, int: 0, count: 0
Yowkees:Keyball61:1: KL: kc: 0x000D, col:  5, row:  7, pressed: 0, time:  6533, int: 0, count: 0
Yowkees:Keyball61:1: KL: kc: 0x420E, col:  4, row:  7, pressed: 1, time:  7143, int: 0, count: 1
kYowkees:Keyball61:1: KL: kc: 0x420E, col:  4, row:  7, pressed: 0, time:  7273, int: 0, count: 1
Yowkees:Keyball61:1: KL: kc: 0x420E, col:  4, row:  7, pressed: 1, time:  9465, int: 1, count: 0
Yowkees:Keyball61:1: layer4KL: kc: 0x00F4, col:  5, row:  7, pressed: 1, time:  9633, int: 0, count: 0
Yowkees:Keyball61:1: KL: kc: 0x00F4, col:  5, row:  7, pressed: 0, time:  9747, int: 0, count: 0
Yowkees:Keyball61:1: KL: kc: 0x420E, col:  4, row:  7, pressed: 0, time:  9803, int: 0, count: 0
Yowkees:Keyball61:1: layer0KL: kc: 0x420E, col:  4, row:  7, pressed: 1, time: 11581, int: 0, count: 0
Yowkees:Keyball61:1: layer4KL: kc: 0x00F4, col:  5, row:  7, pressed: 1, time: 11799, int: 0, count: 0
```

## Next steps - modify config.js to use OSX notifications
At this point I think config.js needs to be modified to use OSX notis instead of WindowsToaster... I will come back to this at some point and submit a PR if I figure it out.

Submitted a PR to add usage field to config.js

Also found that node index requires sudo permissions on OSX, see https://github.com/node-hid/node-hid/issues/64#issuecomment-186433000

**Comment by geneshairzan** [comment]
@g-simmons  Hi Bro, thank for your feedback.. i adding this to main page/ readme
